name: 'Python package'
description: 'Builds and published a Python package to pypi'
inputs:
  pypiApiToken:
    required: true
    description: API token for publish pypi package

runs:
  using: 'composite'
  steps:
    - name: Extract version from tag
      id: version
      run: |
        TAG=${GITHUB_REF##*/}
        echo "PACKAGE_VERSION=${TAG#v}" >> $GITHUB_ENV
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Build the package
      run: |
        pip install -e .[build]
        python -m build
      env:
        PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      shell: bash

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        user: __token__
        password: ${{ inputs.pypiApiToken }}
