name: Publish Python Package

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build-container
        with:
          user: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Build the package
        run: |
          pip install -e .[build]
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v2.1.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
